services:
  - type: web
    name: college-internship-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: UPLOAD_DIR
        value: ./uploads
